// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Milaneli.FapOnline.Testes.Cenarios
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CadastroPessoaFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "CadastroPessoa.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "CadastroPessoa", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "CadastroPessoa")))
            {
                global::Milaneli.FapOnline.Testes.Cenarios.CadastroPessoaFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa nome completo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaNomeCompleto()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa nome completo", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 7
 testRunner.When("não informo nome completo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 8
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 10
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 15
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 16
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 19
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 20
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 21
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 22
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 23
 testRunner.Then("é exibida a mensagem \"Campo obrigatório\" abaixo do campo nome completo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa CPF")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaCPF()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa CPF", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 27
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 28
 testRunner.And("não informo CPF", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 29
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 30
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 31
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 32
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 33
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 34
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 35
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 36
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 37
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 38
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 39
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 40
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 41
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 42
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 43
 testRunner.Then("é exibida a mensagem \"Campo obrigatório\" abaixo do campo CPF", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa CEP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaCEP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa CEP", ((string[])(null)));
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 47
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 48
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 49
 testRunner.And("não informo CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 50
 testRunner.And("informo endereço \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 51
 testRunner.And("informo cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 52
 testRunner.And("informo bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 53
 testRunner.And("informo estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 54
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 55
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 56
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 57
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 58
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 59
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 60
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 61
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 62
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 63
 testRunner.Then("é exibida a mensagem \"Campo obrigatório\" abaixo do campo CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa endereço")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaEndereco()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa endereço", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line 66
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 67
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 68
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 69
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 70
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 71
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 72
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 73
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 74
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 75
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 76
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 77
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 78
 testRunner.And("limpo o campo endereço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 79
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 80
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 81
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 82
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 83
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 84
 testRunner.Then("é exibida a mensagem \"Campo obrigatório\" abaixo do campo endereço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa cidade")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaCidade()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa cidade", ((string[])(null)));
#line 86
this.ScenarioSetup(scenarioInfo);
#line 87
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 88
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 89
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 90
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 91
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 92
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 93
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 94
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 95
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 96
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 97
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 98
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 99
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 100
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 101
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 102
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 103
 testRunner.And("limpo o campo cidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 104
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 105
 testRunner.Then("é exibida a mensagem \"Campo obrigatório\" abaixo do campo cidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa bairro")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaBairro()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa bairro", ((string[])(null)));
#line 107
this.ScenarioSetup(scenarioInfo);
#line 108
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 109
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 110
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 111
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 112
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 113
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 114
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 115
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 116
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 117
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 118
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 119
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 120
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 121
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 122
 testRunner.And("limpo o campo bairro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 123
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 124
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 125
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 126
 testRunner.Then("é exibida a mensagem \"Campo obrigatório\" abaixo do campo bairro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa estado")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaEstado()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa estado", ((string[])(null)));
#line 128
this.ScenarioSetup(scenarioInfo);
#line 129
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 130
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 131
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 132
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 133
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 134
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 135
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 136
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 137
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 138
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 139
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 140
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 141
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 142
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 143
 testRunner.And("limpo o campo estado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 144
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 145
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 146
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 147
 testRunner.Then("é exibida a mensagem \"Campo obrigatório\" abaixo do campo estado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa número")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaNumero()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa número", ((string[])(null)));
#line 149
this.ScenarioSetup(scenarioInfo);
#line 150
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 151
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 152
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 153
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 154
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 155
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 156
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 157
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 158
 testRunner.And("não informo número", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 159
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 160
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 161
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 162
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 163
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 164
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 165
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 166
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 167
 testRunner.Then("é exibida a mensagem \"Campo obrigatório\" abaixo do campo número", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa sexo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaSexo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa sexo", ((string[])(null)));
#line 169
this.ScenarioSetup(scenarioInfo);
#line 170
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 171
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 172
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 173
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 174
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 175
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 176
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 177
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 178
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 179
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 180
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 181
 testRunner.And("não informo sexo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 182
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 183
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 184
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 185
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 186
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 187
 testRunner.Then("é exibida a mensagem \"Selecione uma opção\" abaixo do campo sexo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa não informa tipo da necessidade")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaNaoInformaTipoDaNecessidade()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa não informa tipo da necessidade", ((string[])(null)));
#line 189
this.ScenarioSetup(scenarioInfo);
#line 190
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 191
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 192
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 193
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 194
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 195
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 196
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 197
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 198
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 199
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 200
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 201
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 202
 testRunner.And("informo sim para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 203
 testRunner.And("não informo tipo da necessidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 204
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 205
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 206
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 207
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 208
 testRunner.Then("é exibida a mensagem \"Selecione uma opção\" abaixo do campo tipo da necessidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa informa letras no campo CPF")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaInformaLetrasNoCampoCPF()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa informa letras no campo CPF", ((string[])(null)));
#line 210
this.ScenarioSetup(scenarioInfo);
#line 211
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 212
 testRunner.When("informo CPF \"abc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 213
 testRunner.And("tiro o foco do campo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 214
 testRunner.Then("é exibida a mensagem \"CPF incompleto\" abaixo do campo CPF", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 215
 testRunner.And("o campo CPF deve conter \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa informa letras no campo CEP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaInformaLetrasNoCampoCEP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa informa letras no campo CEP", ((string[])(null)));
#line 217
this.ScenarioSetup(scenarioInfo);
#line 218
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 219
 testRunner.When("informo CEP \"abc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 220
 testRunner.And("tiro o foco do campo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 221
 testRunner.Then("é exibida a mensagem \"CEP incompleto\" abaixo do campo CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 222
 testRunner.And("o campo CEP deve conter \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa informa letras no campo telefone")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaInformaLetrasNoCampoTelefone()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa informa letras no campo telefone", ((string[])(null)));
#line 224
this.ScenarioSetup(scenarioInfo);
#line 225
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 226
 testRunner.When("informo telefone \"abc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 227
 testRunner.And("tiro o foco do campo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 228
 testRunner.Then("o campo telefone deve conter \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa informa que possui necessidades especiais")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaInformaQuePossuiNecessidadesEspeciais()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa informa que possui necessidades especiais", ((string[])(null)));
#line 230
this.ScenarioSetup(scenarioInfo);
#line 231
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 232
 testRunner.When("informo sim para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 233
 testRunner.Then("deve ser exibido o campo tipo da necessidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa informa que não possui necessidades especiais")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaInformaQueNaoPossuiNecessidadesEspeciais()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa informa que não possui necessidades especiais", ((string[])(null)));
#line 235
this.ScenarioSetup(scenarioInfo);
#line 236
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 237
 testRunner.And("informo sim para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 238
 testRunner.And("deve ser exibido o campo tipo da necessidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 239
 testRunner.When("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 240
 testRunner.Then("não deve ser exibido o campo tipo da necessidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pessoa informa dados válidos")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CadastroPessoa")]
        public virtual void PessoaInformaDadosValidos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pessoa informa dados válidos", ((string[])(null)));
#line 242
this.ScenarioSetup(scenarioInfo);
#line 243
 testRunner.Given("que acesso o cadastro de pessoas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 244
 testRunner.When("informo nome completo \"Rogério Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 245
 testRunner.And("informo CPF \"56772009800\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 246
 testRunner.And("informo CEP \"09020160\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 247
 testRunner.And("aguardo carregar o endereco \"Rua Dona Elisa Fláquer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 248
 testRunner.And("aguardo carregar a cidade \"Santo André\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 249
 testRunner.And("aguardo carregar o bairro \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 250
 testRunner.And("aguardo carregar o estado \"SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 251
 testRunner.And("informo número \"70\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 252
 testRunner.And("informo complemento \"14º andar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 253
 testRunner.And("informo e-mail \"rogerio.silva@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 254
 testRunner.And("informo sexo masculino", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 255
 testRunner.And("informo não para necessidades especiais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 256
 testRunner.And("informo telefone \"1134586222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 257
 testRunner.And("informo celular \"11989584238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 258
 testRunner.And("informo observações \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 259
 testRunner.And("pressiono o botão cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 260
 testRunner.Then("é exibida a mensagem \"Seu cadastro foi concluído com sucesso\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
